### ISSUE TITLE
Using SecretsManager with a PlainText value causes the JObject Parse to fail

### ISSUE THREAD

**Issue by benjackson01** [aws/aws-dotnet-extensions-configuration#37]
- Create a secret in Secrets Manager as PlainText
- Try and reference secret using the path below in progam.cs for example:

`config.AddSystemsManager($"/aws/reference/secretsmanager/settings/SecretKey");`

- Following exception occurs in the JsonConfigurationParser (Line 61) when trying to load the JObject:

   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Amazon.Extensions.Configuration.SystemsManager.Internal.JsonConfigurationParser.ParseInput(TextReader input) in C:\Development\SmartGit\aws-dotnet-extensions-configuration\src\Amazon.Extensions.Configuration.SystemsManager\Internal\JsonConfigurationParser.cs:line 61
   at Amazon.Extensions.Configuration.SystemsManager.Internal.JsonConfigurationParser.Parse(String input) in C:\Development\SmartGit\aws-dotnet-extensions-configuration\src\Amazon.Extensions.Configuration.SystemsManager\Internal\JsonConfigurationParser.cs:line 52
   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParameterAsync() in C:\Development\SmartGit\aws-dotnet-extensions-configuration\src\Amazon.Extensions.Configuration.SystemsManager\Internal\SystemsManagerProcessor.cs:line 88
   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetDataAsync() in C:\Development\SmartGit\aws-dotnet-extensions-configuration\src\Amazon.Extensions.Configuration.SystemsManager\Internal\SystemsManagerProcessor.cs:line 47
   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.LoadAsync(Boolean reload) in C:\Development\SmartGit\aws-dotnet-extensions-configuration\src\Amazon.Extensions.Configuration.SystemsManager\SystemsManagerConfigurationProvider.cs:line 109

**Comment by klaytaybai** [comment]
Hi @benjackson01, I've tried to reproduce this, but it worked for me.  Can you please provide info on which versions of our code you are using?  It may also be helpful to provide a link to a repro solution with  non-sensitive data.  Are there any special characters in your secret that you think could possibly break the JSON?

**Comment by benjackson01** [comment]
Hi @klaytaybai ,

I am using the same code cloned from the samples solution project in this repo, so will be the same version as is used. I also have no special characters in the secret as can be seen in the example below. 

I have changed 2 lines to support the secret retrieval as shown below and nothing else:

Program.cs

New line in CreateWebHostBuilder

`config.AddSystemsManager($"/aws/reference/secretsmanager/settings/PlainTextSecret");`

Settings.cs

New property

`public string PlainTextSecret { get; set; }`

This is an example of a secret I am using and how it is setup in secrets manager:

![image](https://user-images.githubusercontent.com/33865533/56039231-b39e8c80-5d2b-11e9-9cd2-c3c1ca355c92.png)

Using a Key/Value works just not the PlainText conversion.

This is the error message from the JsonConfugurationParser: "Unexpected character encountered while parsing value: T. Path '', line 0, position 0."

![image](https://user-images.githubusercontent.com/33865533/56042356-c8325300-5d32-11e9-9322-ac7fb7230d6e.png)

**Comment by ashishdhingra** [comment]
Hi @benjackson01,

Good afternoon.

I was going through the backlog and came across this issue. Kindly verify if this is still an issue with the latest version. As far as I remember, the solution worked fine for me. In case this is no longer an issue, please confirm if this could be closed.

Thanks,
Ashish
