### ISSUE TITLE
Configuring permissions to access the Property Store

### ISSUE THREAD

**Issue by stonkie** [aws/aws-dotnet-extensions-configuration#39]
I have been battling this error and I can't seem to figure it out. My dotnet core application deployed on an EC2 instance just crashes in a loop.

So I tried to launch it directly to get some data and when I run 

```
/usr/bin/dotnet /home/ubuntu/aspnetcoreapp/MySite.dll
```

I get this error

```
Unhandled Exception: Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementException: User: arn:aws:sts::012345678901:assumed-role/CodeStarWorker-mysite-WebApp/i-0123456789badcafe is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-east-1:012345678901:parameter/PropertyStoreRootName ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParametersByPathAsync()
```

I went in IAM and tried to add the following policy on the aws-codestar-service-role role, but that didn't work.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ssm:DescribeParameters",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ssm:GetParameterHistory",
                "ssm:GetParametersByPath",
                "ssm:GetParameters",
                "ssm:GetParameter"
            ],
            "Resource": "arn:aws:ssm:us-east-1:012345678901:parameter/*"
        }
    ]
}
```

That didn't work either.

My code looks pretty much like the samples...

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    private static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration(builder =>
            {
                if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") != "Development")
                {
                    builder.AddSystemsManager(source =>
                    {
                        source.Path = "/MySite";
                        source.ReloadAfter = TimeSpan.FromMinutes(5);
                    }); 
                }
            })
            .UseStartup<Startup>();
}
```

012345678901 is what I understand to be my unique user ID
0123456789badcafe is a bunch of hexa that doesn't seem to match anything I know of, but I anonymized it just in case.

What I want to store in the Property Store are the AWS key and secret, but I feel like I need those already in the app to retrieve properties. 

Am I trying to drive in screws with a hammer here? Or is there something else I'm missing entirely?

**Comment by klaytaybai** [comment]
To get the permissions correct for your role, you will need to modify the policy for the CodeStarWorker-mysite-WebApp role, which seems to be different than the aws-codestar-service-role you mention.

You are correct about the user id.

The 0123456789badcafe is your [role session name](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html).

Take a look at this [documentation on configuring credentials](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html).

**Comment by stonkie** [comment]
Hi,

Ah man, I was so close! None of the tutorials or documentation I read mentioned changing permissions on that role to allow access to the property for the EC2 instance so I thought I was going the wrong way with the permissions and that I was just using it all wrong.

Thanks for your advice!
Kevin
