### ISSUE TITLE
Resource Temporarily Unavailable

### ISSUE THREAD

**Issue by avi1989** [aws/aws-dotnet-extensions-configuration#63]
We've been using this library for a few months without any issues in aws govcloud. We are planning to move one of our environments out of GovCloud into us-east-2 and we're running into the following exception while attempting to access our configuration.

> Unhandled Exception: System.Net.Http.HttpRequestException: Resource temporarily unavailable ---> System.Net.Sockets.SocketException: Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParametersByPathAsync()
   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetDataAsync()
   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.LoadAsync(Boolean reload)
   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at CoverMe.Notes.HostedApi.Program.Main(String[] args) in /src/CoverMe.Notes.HostedApi/Program.cs:line 18

I've added an appropriate IAM role to the ec2 instance to access SSM. I am able to access SSM with the aws cli on the ec2 instance. 

We're connecting to SSM using the code defined below

```csharp
return builder.ConfigureAppConfiguration((wb, cb) =>
{
    var env = wb.HostingEnvironment;
    cb
        .SetBasePath(env.ContentRootPath)
        .AddJsonFile("appsettings.json", optional: true,
                     reloadOnChange: true)
        .AddJsonFile($"appsettings.{env.EnvironmentName}.json",
                     optional: true, reloadOnChange: true)
        .AddEnvironmentVariables();

    string awsPath = Environment.GetEnvironmentVariable("AWS_CONFIG_PATH");

    if (!string.IsNullOrWhiteSpace(awsPath))
    {
        cb.AddSystemsManager(awsPath);
    }
});
```
Am I missing something really basic here? I just can't figure out why this is not working.

**Comment by jhtodd** [comment]
I'm getting the same error when testing locally, but only when running inside a Docker container. Things seem to work normally when running standalone Kestrel or under IIS Express. I haven't tried in an actual AWS environment yet.

**Comment by jhtodd** [comment]
@avi1989 Are you running under Docker? The only context in which I've been seeing reports of this particular error is related to how Docker handles IPv6 vs. IPv4 forwarding. I was able to solve my problem simply by switching from Windows to Linux containers (which I meant to do from the start anyway).

I wonder if something is different in how your application is running under us-east-2? I don't know anything about GovCloud. Was the transition just a simple lift-and-shift to the new region?

**Comment by avi1989** [comment]
Interesting. I am running docker in both govcloud and us-east-2 on linux containers.

Since everything we are running is in a docker swarm, I just created the RDS box on us-east-2, added the ssm settings and pushed the image to the ecr in us-east-2 and tried running the image. It should have been a very straightforward migration.

I connected to the container in us-east-2, installed awscli and verified that the container itself was able to connect to ssm. 

I spent some time yesterday analyzing the boxes on both govcloud and ec2 and I think the only difference between the boxes is that the us-east-2 box uses a newer version of the docker engine. Let me try building a new ec2 instance with the same version of docker we have in govcloud and see if that works. That might help us get to the bottom of this.

**Comment by avi1989** [comment]
I installed the same version of docker on my us-east-2 server and it still does not work. In my head that rules out a docker networking issue.

**Comment by ashishdhingra** [comment]
Hi @avi1989,

Good afternoon.

Please advise if this is still an issue or if this could be closed. In case this is still an issue, kindly provide sample code solution and AWS configuration settings, for us to troubleshoot the issue.

Thanks,
Ashish

**Comment by ameer-thasthahir** [comment]
Hi, Facing the same issue while running it in EKS? Any adivce?
